version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "ToDoList"
      POSTGRES_USER: "Ivan"
      POSTGRES_PASSWORD: "1q2w3e4r"
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis_container
    environment:
      - REDIS_PASSWORD=1q2w3e4r
      - REDIS_USER=Ivan
      - REDIS_USER_PASSWORD=1q2w3e4r
    ports:
      - "6379:6379"